version: "3.7"

services:
  workspace:
    image: php:fpm-alpine
    container_name: workspace
    restart: unless-stopped
    volumes:
      - ../:/var/www/html/
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../logs/nginx:/var/log/nginx/

  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
